/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Phone number information
    /// </summary>
    [DataContract]
    public partial class DevicePhoneNumberInfo :  IEquatable<DevicePhoneNumberInfo>, IValidatableObject
    {
        /// <summary>
        /// Payment type. &#39;External&#39; is returned for forwarded numbers which are not terminated in the RingCentral phone system &#x3D; [&#39;External&#39;, &#39;TollFree&#39;, &#39;Local&#39;]
        /// </summary>
        /// <value>Payment type. &#39;External&#39; is returned for forwarded numbers which are not terminated in the RingCentral phone system &#x3D; [&#39;External&#39;, &#39;TollFree&#39;, &#39;Local&#39;]</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PaymentTypeEnum
        {
            /// <summary>
            /// Enum External for value: External
            /// </summary>
            [EnumMember(Value = "External")]
            External = 1,

            /// <summary>
            /// Enum TollFree for value: TollFree
            /// </summary>
            [EnumMember(Value = "TollFree")]
            TollFree = 2,

            /// <summary>
            /// Enum Local for value: Local
            /// </summary>
            [EnumMember(Value = "Local")]
            Local = 3

        }

        /// <summary>
        /// Payment type. &#39;External&#39; is returned for forwarded numbers which are not terminated in the RingCentral phone system &#x3D; [&#39;External&#39;, &#39;TollFree&#39;, &#39;Local&#39;]
        /// </summary>
        /// <value>Payment type. &#39;External&#39; is returned for forwarded numbers which are not terminated in the RingCentral phone system &#x3D; [&#39;External&#39;, &#39;TollFree&#39;, &#39;Local&#39;]</value>
        [DataMember(Name="paymentType", EmitDefaultValue=false)]
        public PaymentTypeEnum? PaymentType { get; set; }
        /// <summary>
        /// Defines UsageType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum UsageTypeEnum
        {
            /// <summary>
            /// Enum CompanyNumber for value: CompanyNumber
            /// </summary>
            [EnumMember(Value = "CompanyNumber")]
            CompanyNumber = 1,

            /// <summary>
            /// Enum MainCompanyNumber for value: MainCompanyNumber
            /// </summary>
            [EnumMember(Value = "MainCompanyNumber")]
            MainCompanyNumber = 2,

            /// <summary>
            /// Enum AdditionalCompanyNumber for value: AdditionalCompanyNumber
            /// </summary>
            [EnumMember(Value = "AdditionalCompanyNumber")]
            AdditionalCompanyNumber = 3,

            /// <summary>
            /// Enum DirectNumber for value: DirectNumber
            /// </summary>
            [EnumMember(Value = "DirectNumber")]
            DirectNumber = 4,

            /// <summary>
            /// Enum CompanyFaxNumber for value: CompanyFaxNumber
            /// </summary>
            [EnumMember(Value = "CompanyFaxNumber")]
            CompanyFaxNumber = 5,

            /// <summary>
            /// Enum ForwardedNumber for value: ForwardedNumber
            /// </summary>
            [EnumMember(Value = "ForwardedNumber")]
            ForwardedNumber = 6,

            /// <summary>
            /// Enum ForwardedCompanyNumber for value: ForwardedCompanyNumber
            /// </summary>
            [EnumMember(Value = "ForwardedCompanyNumber")]
            ForwardedCompanyNumber = 7,

            /// <summary>
            /// Enum ContactCenterNumber for value: ContactCenterNumber
            /// </summary>
            [EnumMember(Value = "ContactCenterNumber")]
            ContactCenterNumber = 8

        }

        /// <summary>
        /// Gets or Sets UsageType
        /// </summary>
        [DataMember(Name="usageType", EmitDefaultValue=false)]
        public UsageTypeEnum? UsageType { get; set; }
        /// <summary>
        /// Type of a phone number
        /// </summary>
        /// <value>Type of a phone number</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum VoiceFax for value: VoiceFax
            /// </summary>
            [EnumMember(Value = "VoiceFax")]
            VoiceFax = 1,

            /// <summary>
            /// Enum FaxOnly for value: FaxOnly
            /// </summary>
            [EnumMember(Value = "FaxOnly")]
            FaxOnly = 2,

            /// <summary>
            /// Enum VoiceOnly for value: VoiceOnly
            /// </summary>
            [EnumMember(Value = "VoiceOnly")]
            VoiceOnly = 3

        }

        /// <summary>
        /// Type of a phone number
        /// </summary>
        /// <value>Type of a phone number</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DevicePhoneNumberInfo" /> class.
        /// </summary>
        /// <param name="id">Internal identifier of a phone number.</param>
        /// <param name="country">country.</param>
        /// <param name="paymentType">Payment type. &#39;External&#39; is returned for forwarded numbers which are not terminated in the RingCentral phone system &#x3D; [&#39;External&#39;, &#39;TollFree&#39;, &#39;Local&#39;].</param>
        /// <param name="phoneNumber">Phone number.</param>
        /// <param name="usageType">usageType.</param>
        /// <param name="type">Type of a phone number.</param>
        public DevicePhoneNumberInfo(long id = default(long), DevicePhoneNumberCountryInfo country = default(DevicePhoneNumberCountryInfo), PaymentTypeEnum? paymentType = default(PaymentTypeEnum?), string phoneNumber = default(string), UsageTypeEnum? usageType = default(UsageTypeEnum?), TypeEnum? type = default(TypeEnum?))
        {
            this.Id = id;
            this.Country = country;
            this.PaymentType = paymentType;
            this.PhoneNumber = phoneNumber;
            this.UsageType = usageType;
            this.Type = type;
        }

        /// <summary>
        /// Internal identifier of a phone number
        /// </summary>
        /// <value>Internal identifier of a phone number</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public DevicePhoneNumberCountryInfo Country { get; set; }


        /// <summary>
        /// Phone number
        /// </summary>
        /// <value>Phone number</value>
        [DataMember(Name="phoneNumber", EmitDefaultValue=false)]
        public string PhoneNumber { get; set; }



        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DevicePhoneNumberInfo {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  PaymentType: ").Append(PaymentType).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  UsageType: ").Append(UsageType).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DevicePhoneNumberInfo);
        }

        /// <summary>
        /// Returns true if DevicePhoneNumberInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of DevicePhoneNumberInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DevicePhoneNumberInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.PaymentType == input.PaymentType ||
                    (this.PaymentType != null &&
                    this.PaymentType.Equals(input.PaymentType))
                ) && 
                (
                    this.PhoneNumber == input.PhoneNumber ||
                    (this.PhoneNumber != null &&
                    this.PhoneNumber.Equals(input.PhoneNumber))
                ) && 
                (
                    this.UsageType == input.UsageType ||
                    (this.UsageType != null &&
                    this.UsageType.Equals(input.UsageType))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.PaymentType != null)
                    hashCode = hashCode * 59 + this.PaymentType.GetHashCode();
                if (this.PhoneNumber != null)
                    hashCode = hashCode * 59 + this.PhoneNumber.GetHashCode();
                if (this.UsageType != null)
                    hashCode = hashCode * 59 + this.UsageType.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PhoneNumber (string) maxLength
            if(this.PhoneNumber != null && this.PhoneNumber.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumber, length must be less than 128.", new [] { "PhoneNumber" });
            }

            // PhoneNumber (string) minLength
            if(this.PhoneNumber != null && this.PhoneNumber.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PhoneNumber, length must be greater than 0.", new [] { "PhoneNumber" });
            }

            yield break;
        }
    }

}
