/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Address for emergency cases. The same emergency address is assigned to all the numbers of one device
    /// </summary>
    [DataContract]
    public partial class EmergencyServiceAddressResource :  IEquatable<EmergencyServiceAddressResource>, IValidatableObject
    {
        /// <summary>
        /// Resulting status of emergency address synchronization. Returned if &#x60;syncEmergencyAddress&#x60; parameter is set to &#39;True&#39;
        /// </summary>
        /// <value>Resulting status of emergency address synchronization. Returned if &#x60;syncEmergencyAddress&#x60; parameter is set to &#39;True&#39;</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SyncStatusEnum
        {
            /// <summary>
            /// Enum Verified for value: Verified
            /// </summary>
            [EnumMember(Value = "Verified")]
            Verified = 1,

            /// <summary>
            /// Enum Updated for value: Updated
            /// </summary>
            [EnumMember(Value = "Updated")]
            Updated = 2,

            /// <summary>
            /// Enum Deleted for value: Deleted
            /// </summary>
            [EnumMember(Value = "Deleted")]
            Deleted = 3,

            /// <summary>
            /// Enum NotRequired for value: NotRequired
            /// </summary>
            [EnumMember(Value = "NotRequired")]
            NotRequired = 4,

            /// <summary>
            /// Enum Unsupported for value: Unsupported
            /// </summary>
            [EnumMember(Value = "Unsupported")]
            Unsupported = 5,

            /// <summary>
            /// Enum Failed for value: Failed
            /// </summary>
            [EnumMember(Value = "Failed")]
            Failed = 6

        }

        /// <summary>
        /// Resulting status of emergency address synchronization. Returned if &#x60;syncEmergencyAddress&#x60; parameter is set to &#39;True&#39;
        /// </summary>
        /// <value>Resulting status of emergency address synchronization. Returned if &#x60;syncEmergencyAddress&#x60; parameter is set to &#39;True&#39;</value>
        [DataMember(Name="syncStatus", EmitDefaultValue=false)]
        public SyncStatusEnum? SyncStatus { get; set; }
        /// <summary>
        /// Status of digital line provisioning
        /// </summary>
        /// <value>Status of digital line provisioning</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LineProvisioningStatusEnum
        {
            /// <summary>
            /// Enum Provisioning for value: Provisioning
            /// </summary>
            [EnumMember(Value = "Provisioning")]
            Provisioning = 1,

            /// <summary>
            /// Enum Valid for value: Valid
            /// </summary>
            [EnumMember(Value = "Valid")]
            Valid = 2,

            /// <summary>
            /// Enum Invalid for value: Invalid
            /// </summary>
            [EnumMember(Value = "Invalid")]
            Invalid = 3

        }

        /// <summary>
        /// Status of digital line provisioning
        /// </summary>
        /// <value>Status of digital line provisioning</value>
        [DataMember(Name="lineProvisioningStatus", EmitDefaultValue=false)]
        public LineProvisioningStatusEnum? LineProvisioningStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmergencyServiceAddressResource" /> class.
        /// </summary>
        /// <param name="street">street.</param>
        /// <param name="street2">street2.</param>
        /// <param name="city">city.</param>
        /// <param name="zip">zip.</param>
        /// <param name="customerName">customerName.</param>
        /// <param name="state">State/province name.</param>
        /// <param name="stateId">Internal identifier of a state.</param>
        /// <param name="stateIsoCode">ISO code of a state.</param>
        /// <param name="stateName">Full name of a state.</param>
        /// <param name="countryId">Internal identifier of a country.</param>
        /// <param name="countryIsoCode">ISO code of a country.</param>
        /// <param name="country">Country name.</param>
        /// <param name="countryName">Full name of a country.</param>
        /// <param name="outOfCountry">Specifies if emergency address is out of country.</param>
        /// <param name="syncStatus">Resulting status of emergency address synchronization. Returned if &#x60;syncEmergencyAddress&#x60; parameter is set to &#39;True&#39;.</param>
        /// <param name="additionalCustomerName">Name of an additional contact person. Should be specified for countries except the US, Canada, the UK and Australia..</param>
        /// <param name="customerEmail">Email of a primary contact person (receiver). Should be specified for countries except the US, Canada, the UK and Australia..</param>
        /// <param name="additionalCustomerEmail">Email of an additional contact person. Should be specified for countries except the US, Canada, the UK and Australia..</param>
        /// <param name="customerPhone">Phone number of a primary contact person (receiver). Should be specified for countries except the US, Canada, the UK and Australia.</param>
        /// <param name="additionalCustomerPhone">Phone number of an additional contact person. Should be specified for countries except the US, Canada, the UK &amp; Australia..</param>
        /// <param name="lineProvisioningStatus">Status of digital line provisioning.</param>
        /// <param name="taxId">Internal identifier of a tax.</param>
        public EmergencyServiceAddressResource(string street = default(string), string street2 = default(string), string city = default(string), string zip = default(string), string customerName = default(string), string state = default(string), string stateId = default(string), string stateIsoCode = default(string), string stateName = default(string), string countryId = default(string), string countryIsoCode = default(string), string country = default(string), string countryName = default(string), bool outOfCountry = default(bool), SyncStatusEnum? syncStatus = default(SyncStatusEnum?), string additionalCustomerName = default(string), string customerEmail = default(string), string additionalCustomerEmail = default(string), string customerPhone = default(string), string additionalCustomerPhone = default(string), LineProvisioningStatusEnum? lineProvisioningStatus = default(LineProvisioningStatusEnum?), string taxId = default(string))
        {
            this.Street = street;
            this.Street2 = street2;
            this.City = city;
            this.Zip = zip;
            this.CustomerName = customerName;
            this.State = state;
            this.StateId = stateId;
            this.StateIsoCode = stateIsoCode;
            this.StateName = stateName;
            this.CountryId = countryId;
            this.CountryIsoCode = countryIsoCode;
            this.Country = country;
            this.CountryName = countryName;
            this.OutOfCountry = outOfCountry;
            this.SyncStatus = syncStatus;
            this.AdditionalCustomerName = additionalCustomerName;
            this.CustomerEmail = customerEmail;
            this.AdditionalCustomerEmail = additionalCustomerEmail;
            this.CustomerPhone = customerPhone;
            this.AdditionalCustomerPhone = additionalCustomerPhone;
            this.LineProvisioningStatus = lineProvisioningStatus;
            this.TaxId = taxId;
        }

        /// <summary>
        /// Gets or Sets Street
        /// </summary>
        [DataMember(Name="street", EmitDefaultValue=false)]
        public string Street { get; set; }

        /// <summary>
        /// Gets or Sets Street2
        /// </summary>
        [DataMember(Name="street2", EmitDefaultValue=false)]
        public string Street2 { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        [DataMember(Name="city", EmitDefaultValue=false)]
        public string City { get; set; }

        /// <summary>
        /// Gets or Sets Zip
        /// </summary>
        [DataMember(Name="zip", EmitDefaultValue=false)]
        public string Zip { get; set; }

        /// <summary>
        /// Gets or Sets CustomerName
        /// </summary>
        [DataMember(Name="customerName", EmitDefaultValue=false)]
        public string CustomerName { get; set; }

        /// <summary>
        /// State/province name
        /// </summary>
        /// <value>State/province name</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// Internal identifier of a state
        /// </summary>
        /// <value>Internal identifier of a state</value>
        [DataMember(Name="stateId", EmitDefaultValue=false)]
        public string StateId { get; set; }

        /// <summary>
        /// ISO code of a state
        /// </summary>
        /// <value>ISO code of a state</value>
        [DataMember(Name="stateIsoCode", EmitDefaultValue=false)]
        public string StateIsoCode { get; set; }

        /// <summary>
        /// Full name of a state
        /// </summary>
        /// <value>Full name of a state</value>
        [DataMember(Name="stateName", EmitDefaultValue=false)]
        public string StateName { get; set; }

        /// <summary>
        /// Internal identifier of a country
        /// </summary>
        /// <value>Internal identifier of a country</value>
        [DataMember(Name="countryId", EmitDefaultValue=false)]
        public string CountryId { get; set; }

        /// <summary>
        /// ISO code of a country
        /// </summary>
        /// <value>ISO code of a country</value>
        [DataMember(Name="countryIsoCode", EmitDefaultValue=false)]
        public string CountryIsoCode { get; set; }

        /// <summary>
        /// Country name
        /// </summary>
        /// <value>Country name</value>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }

        /// <summary>
        /// Full name of a country
        /// </summary>
        /// <value>Full name of a country</value>
        [DataMember(Name="countryName", EmitDefaultValue=false)]
        public string CountryName { get; set; }

        /// <summary>
        /// Specifies if emergency address is out of country
        /// </summary>
        /// <value>Specifies if emergency address is out of country</value>
        [DataMember(Name="outOfCountry", EmitDefaultValue=false)]
        public bool OutOfCountry { get; set; }


        /// <summary>
        /// Name of an additional contact person. Should be specified for countries except the US, Canada, the UK and Australia.
        /// </summary>
        /// <value>Name of an additional contact person. Should be specified for countries except the US, Canada, the UK and Australia.</value>
        [DataMember(Name="additionalCustomerName", EmitDefaultValue=false)]
        public string AdditionalCustomerName { get; set; }

        /// <summary>
        /// Email of a primary contact person (receiver). Should be specified for countries except the US, Canada, the UK and Australia.
        /// </summary>
        /// <value>Email of a primary contact person (receiver). Should be specified for countries except the US, Canada, the UK and Australia.</value>
        [DataMember(Name="customerEmail", EmitDefaultValue=false)]
        public string CustomerEmail { get; set; }

        /// <summary>
        /// Email of an additional contact person. Should be specified for countries except the US, Canada, the UK and Australia.
        /// </summary>
        /// <value>Email of an additional contact person. Should be specified for countries except the US, Canada, the UK and Australia.</value>
        [DataMember(Name="additionalCustomerEmail", EmitDefaultValue=false)]
        public string AdditionalCustomerEmail { get; set; }

        /// <summary>
        /// Phone number of a primary contact person (receiver). Should be specified for countries except the US, Canada, the UK and Australia
        /// </summary>
        /// <value>Phone number of a primary contact person (receiver). Should be specified for countries except the US, Canada, the UK and Australia</value>
        [DataMember(Name="customerPhone", EmitDefaultValue=false)]
        public string CustomerPhone { get; set; }

        /// <summary>
        /// Phone number of an additional contact person. Should be specified for countries except the US, Canada, the UK &amp; Australia.
        /// </summary>
        /// <value>Phone number of an additional contact person. Should be specified for countries except the US, Canada, the UK &amp; Australia.</value>
        [DataMember(Name="additionalCustomerPhone", EmitDefaultValue=false)]
        public string AdditionalCustomerPhone { get; set; }


        /// <summary>
        /// Internal identifier of a tax
        /// </summary>
        /// <value>Internal identifier of a tax</value>
        [DataMember(Name="taxId", EmitDefaultValue=false)]
        public string TaxId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmergencyServiceAddressResource {\n");
            sb.Append("  Street: ").Append(Street).Append("\n");
            sb.Append("  Street2: ").Append(Street2).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Zip: ").Append(Zip).Append("\n");
            sb.Append("  CustomerName: ").Append(CustomerName).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  StateId: ").Append(StateId).Append("\n");
            sb.Append("  StateIsoCode: ").Append(StateIsoCode).Append("\n");
            sb.Append("  StateName: ").Append(StateName).Append("\n");
            sb.Append("  CountryId: ").Append(CountryId).Append("\n");
            sb.Append("  CountryIsoCode: ").Append(CountryIsoCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  CountryName: ").Append(CountryName).Append("\n");
            sb.Append("  OutOfCountry: ").Append(OutOfCountry).Append("\n");
            sb.Append("  SyncStatus: ").Append(SyncStatus).Append("\n");
            sb.Append("  AdditionalCustomerName: ").Append(AdditionalCustomerName).Append("\n");
            sb.Append("  CustomerEmail: ").Append(CustomerEmail).Append("\n");
            sb.Append("  AdditionalCustomerEmail: ").Append(AdditionalCustomerEmail).Append("\n");
            sb.Append("  CustomerPhone: ").Append(CustomerPhone).Append("\n");
            sb.Append("  AdditionalCustomerPhone: ").Append(AdditionalCustomerPhone).Append("\n");
            sb.Append("  LineProvisioningStatus: ").Append(LineProvisioningStatus).Append("\n");
            sb.Append("  TaxId: ").Append(TaxId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmergencyServiceAddressResource);
        }

        /// <summary>
        /// Returns true if EmergencyServiceAddressResource instances are equal
        /// </summary>
        /// <param name="input">Instance of EmergencyServiceAddressResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmergencyServiceAddressResource input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Street == input.Street ||
                    (this.Street != null &&
                    this.Street.Equals(input.Street))
                ) && 
                (
                    this.Street2 == input.Street2 ||
                    (this.Street2 != null &&
                    this.Street2.Equals(input.Street2))
                ) && 
                (
                    this.City == input.City ||
                    (this.City != null &&
                    this.City.Equals(input.City))
                ) && 
                (
                    this.Zip == input.Zip ||
                    (this.Zip != null &&
                    this.Zip.Equals(input.Zip))
                ) && 
                (
                    this.CustomerName == input.CustomerName ||
                    (this.CustomerName != null &&
                    this.CustomerName.Equals(input.CustomerName))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.StateId == input.StateId ||
                    (this.StateId != null &&
                    this.StateId.Equals(input.StateId))
                ) && 
                (
                    this.StateIsoCode == input.StateIsoCode ||
                    (this.StateIsoCode != null &&
                    this.StateIsoCode.Equals(input.StateIsoCode))
                ) && 
                (
                    this.StateName == input.StateName ||
                    (this.StateName != null &&
                    this.StateName.Equals(input.StateName))
                ) && 
                (
                    this.CountryId == input.CountryId ||
                    (this.CountryId != null &&
                    this.CountryId.Equals(input.CountryId))
                ) && 
                (
                    this.CountryIsoCode == input.CountryIsoCode ||
                    (this.CountryIsoCode != null &&
                    this.CountryIsoCode.Equals(input.CountryIsoCode))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.CountryName == input.CountryName ||
                    (this.CountryName != null &&
                    this.CountryName.Equals(input.CountryName))
                ) && 
                (
                    this.OutOfCountry == input.OutOfCountry ||
                    (this.OutOfCountry != null &&
                    this.OutOfCountry.Equals(input.OutOfCountry))
                ) && 
                (
                    this.SyncStatus == input.SyncStatus ||
                    (this.SyncStatus != null &&
                    this.SyncStatus.Equals(input.SyncStatus))
                ) && 
                (
                    this.AdditionalCustomerName == input.AdditionalCustomerName ||
                    (this.AdditionalCustomerName != null &&
                    this.AdditionalCustomerName.Equals(input.AdditionalCustomerName))
                ) && 
                (
                    this.CustomerEmail == input.CustomerEmail ||
                    (this.CustomerEmail != null &&
                    this.CustomerEmail.Equals(input.CustomerEmail))
                ) && 
                (
                    this.AdditionalCustomerEmail == input.AdditionalCustomerEmail ||
                    (this.AdditionalCustomerEmail != null &&
                    this.AdditionalCustomerEmail.Equals(input.AdditionalCustomerEmail))
                ) && 
                (
                    this.CustomerPhone == input.CustomerPhone ||
                    (this.CustomerPhone != null &&
                    this.CustomerPhone.Equals(input.CustomerPhone))
                ) && 
                (
                    this.AdditionalCustomerPhone == input.AdditionalCustomerPhone ||
                    (this.AdditionalCustomerPhone != null &&
                    this.AdditionalCustomerPhone.Equals(input.AdditionalCustomerPhone))
                ) && 
                (
                    this.LineProvisioningStatus == input.LineProvisioningStatus ||
                    (this.LineProvisioningStatus != null &&
                    this.LineProvisioningStatus.Equals(input.LineProvisioningStatus))
                ) && 
                (
                    this.TaxId == input.TaxId ||
                    (this.TaxId != null &&
                    this.TaxId.Equals(input.TaxId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Street != null)
                    hashCode = hashCode * 59 + this.Street.GetHashCode();
                if (this.Street2 != null)
                    hashCode = hashCode * 59 + this.Street2.GetHashCode();
                if (this.City != null)
                    hashCode = hashCode * 59 + this.City.GetHashCode();
                if (this.Zip != null)
                    hashCode = hashCode * 59 + this.Zip.GetHashCode();
                if (this.CustomerName != null)
                    hashCode = hashCode * 59 + this.CustomerName.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.StateId != null)
                    hashCode = hashCode * 59 + this.StateId.GetHashCode();
                if (this.StateIsoCode != null)
                    hashCode = hashCode * 59 + this.StateIsoCode.GetHashCode();
                if (this.StateName != null)
                    hashCode = hashCode * 59 + this.StateName.GetHashCode();
                if (this.CountryId != null)
                    hashCode = hashCode * 59 + this.CountryId.GetHashCode();
                if (this.CountryIsoCode != null)
                    hashCode = hashCode * 59 + this.CountryIsoCode.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.CountryName != null)
                    hashCode = hashCode * 59 + this.CountryName.GetHashCode();
                if (this.OutOfCountry != null)
                    hashCode = hashCode * 59 + this.OutOfCountry.GetHashCode();
                if (this.SyncStatus != null)
                    hashCode = hashCode * 59 + this.SyncStatus.GetHashCode();
                if (this.AdditionalCustomerName != null)
                    hashCode = hashCode * 59 + this.AdditionalCustomerName.GetHashCode();
                if (this.CustomerEmail != null)
                    hashCode = hashCode * 59 + this.CustomerEmail.GetHashCode();
                if (this.AdditionalCustomerEmail != null)
                    hashCode = hashCode * 59 + this.AdditionalCustomerEmail.GetHashCode();
                if (this.CustomerPhone != null)
                    hashCode = hashCode * 59 + this.CustomerPhone.GetHashCode();
                if (this.AdditionalCustomerPhone != null)
                    hashCode = hashCode * 59 + this.AdditionalCustomerPhone.GetHashCode();
                if (this.LineProvisioningStatus != null)
                    hashCode = hashCode * 59 + this.LineProvisioningStatus.GetHashCode();
                if (this.TaxId != null)
                    hashCode = hashCode * 59 + this.TaxId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
