/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GreetingResource
    /// </summary>
    [DataContract]
    public partial class GreetingResource :  IEquatable<GreetingResource>, IValidatableObject
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum StartRecording for value: StartRecording
            /// </summary>
            [EnumMember(Value = "StartRecording")]
            StartRecording = 1,

            /// <summary>
            /// Enum StopRecording for value: StopRecording
            /// </summary>
            [EnumMember(Value = "StopRecording")]
            StopRecording = 2,

            /// <summary>
            /// Enum AutomaticRecording for value: AutomaticRecording
            /// </summary>
            [EnumMember(Value = "AutomaticRecording")]
            AutomaticRecording = 3

        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// &#39;Default&#39; value specifies that all greetings of that type (in all languages) are default, if at least one greeting (in any language) of the specified type is custom, then &#39;Custom&#39; value is returned.
        /// </summary>
        /// <value>&#39;Default&#39; value specifies that all greetings of that type (in all languages) are default, if at least one greeting (in any language) of the specified type is custom, then &#39;Custom&#39; value is returned.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModeEnum
        {
            /// <summary>
            /// Enum Default for value: Default
            /// </summary>
            [EnumMember(Value = "Default")]
            Default = 1,

            /// <summary>
            /// Enum Custom for value: Custom
            /// </summary>
            [EnumMember(Value = "Custom")]
            Custom = 2

        }

        /// <summary>
        /// &#39;Default&#39; value specifies that all greetings of that type (in all languages) are default, if at least one greeting (in any language) of the specified type is custom, then &#39;Custom&#39; value is returned.
        /// </summary>
        /// <value>&#39;Default&#39; value specifies that all greetings of that type (in all languages) are default, if at least one greeting (in any language) of the specified type is custom, then &#39;Custom&#39; value is returned.</value>
        [DataMember(Name="mode", EmitDefaultValue=false)]
        public ModeEnum? Mode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GreetingResource" /> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="mode">&#39;Default&#39; value specifies that all greetings of that type (in all languages) are default, if at least one greeting (in any language) of the specified type is custom, then &#39;Custom&#39; value is returned..</param>
        public GreetingResource(TypeEnum? type = default(TypeEnum?), ModeEnum? mode = default(ModeEnum?))
        {
            this.Type = type;
            this.Mode = mode;
        }



        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GreetingResource {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GreetingResource);
        }

        /// <summary>
        /// Returns true if GreetingResource instances are equal
        /// </summary>
        /// <param name="input">Instance of GreetingResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GreetingResource input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Mode == input.Mode ||
                    (this.Mode != null &&
                    this.Mode.Equals(input.Mode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Mode != null)
                    hashCode = hashCode * 59 + this.Mode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
