/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Call queue information
    /// </summary>
    [DataContract]
    public partial class PresenceCallQueueInfo :  IEquatable<PresenceCallQueueInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PresenceCallQueueInfo" /> class.
        /// </summary>
        /// <param name="id">Internal identifier of a call queue.</param>
        /// <param name="name">Name of a call queue.</param>
        /// <param name="extensionNumber">Extension number of a call queue.</param>
        /// <param name="editableMemberStatus">Flag allow members to change their queue status.</param>
        public PresenceCallQueueInfo(string id = default(string), string name = default(string), string extensionNumber = default(string), bool editableMemberStatus = default(bool))
        {
            this.Id = id;
            this.Name = name;
            this.ExtensionNumber = extensionNumber;
            this.EditableMemberStatus = editableMemberStatus;
        }

        /// <summary>
        /// Internal identifier of a call queue
        /// </summary>
        /// <value>Internal identifier of a call queue</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Name of a call queue
        /// </summary>
        /// <value>Name of a call queue</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Extension number of a call queue
        /// </summary>
        /// <value>Extension number of a call queue</value>
        [DataMember(Name="extensionNumber", EmitDefaultValue=false)]
        public string ExtensionNumber { get; set; }

        /// <summary>
        /// Flag allow members to change their queue status
        /// </summary>
        /// <value>Flag allow members to change their queue status</value>
        [DataMember(Name="editableMemberStatus", EmitDefaultValue=false)]
        public bool EditableMemberStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PresenceCallQueueInfo {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ExtensionNumber: ").Append(ExtensionNumber).Append("\n");
            sb.Append("  EditableMemberStatus: ").Append(EditableMemberStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PresenceCallQueueInfo);
        }

        /// <summary>
        /// Returns true if PresenceCallQueueInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of PresenceCallQueueInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PresenceCallQueueInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ExtensionNumber == input.ExtensionNumber ||
                    (this.ExtensionNumber != null &&
                    this.ExtensionNumber.Equals(input.ExtensionNumber))
                ) && 
                (
                    this.EditableMemberStatus == input.EditableMemberStatus ||
                    (this.EditableMemberStatus != null &&
                    this.EditableMemberStatus.Equals(input.EditableMemberStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ExtensionNumber != null)
                    hashCode = hashCode * 59 + this.ExtensionNumber.GetHashCode();
                if (this.EditableMemberStatus != null)
                    hashCode = hashCode * 59 + this.EditableMemberStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
