/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing AccountHistoryRecordPublicDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountHistoryRecordPublicDetailsTests
    {
        // TODO uncomment below to declare an instance variable for AccountHistoryRecordPublicDetails
        //private AccountHistoryRecordPublicDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountHistoryRecordPublicDetails
            //instance = new AccountHistoryRecordPublicDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountHistoryRecordPublicDetails
        /// </summary>
        [Test]
        public void AccountHistoryRecordPublicDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AccountHistoryRecordPublicDetails
            //Assert.IsInstanceOf(typeof(AccountHistoryRecordPublicDetails), instance);
        }


        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

    }

}
