/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing AutomaticLocationUpdatesPhoneLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutomaticLocationUpdatesPhoneLineTests
    {
        // TODO uncomment below to declare an instance variable for AutomaticLocationUpdatesPhoneLine
        //private AutomaticLocationUpdatesPhoneLine instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AutomaticLocationUpdatesPhoneLine
            //instance = new AutomaticLocationUpdatesPhoneLine();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AutomaticLocationUpdatesPhoneLine
        /// </summary>
        [Test]
        public void AutomaticLocationUpdatesPhoneLineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AutomaticLocationUpdatesPhoneLine
            //Assert.IsInstanceOf(typeof(AutomaticLocationUpdatesPhoneLine), instance);
        }


        /// <summary>
        /// Test the property 'LineType'
        /// </summary>
        [Test]
        public void LineTypeTest()
        {
            // TODO unit test for the property 'LineType'
        }
        /// <summary>
        /// Test the property 'PhoneInfo'
        /// </summary>
        [Test]
        public void PhoneInfoTest()
        {
            // TODO unit test for the property 'PhoneInfo'
        }

    }

}
