/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CallQueueMemberPresence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CallQueueMemberPresenceTests
    {
        // TODO uncomment below to declare an instance variable for CallQueueMemberPresence
        //private CallQueueMemberPresence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallQueueMemberPresence
            //instance = new CallQueueMemberPresence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallQueueMemberPresence
        /// </summary>
        [Test]
        public void CallQueueMemberPresenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CallQueueMemberPresence
            //Assert.IsInstanceOf(typeof(CallQueueMemberPresence), instance);
        }


        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Test]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }
        /// <summary>
        /// Test the property 'AcceptQueueCalls'
        /// </summary>
        [Test]
        public void AcceptQueueCallsTest()
        {
            // TODO unit test for the property 'AcceptQueueCalls'
        }
        /// <summary>
        /// Test the property 'AcceptCurrentQueueCalls'
        /// </summary>
        [Test]
        public void AcceptCurrentQueueCallsTest()
        {
            // TODO unit test for the property 'AcceptCurrentQueueCalls'
        }

    }

}
