/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CallMonitoringGroupMemberInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CallMonitoringGroupMemberInfoTests
    {
        // TODO uncomment below to declare an instance variable for CallMonitoringGroupMemberInfo
        //private CallMonitoringGroupMemberInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallMonitoringGroupMemberInfo
            //instance = new CallMonitoringGroupMemberInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallMonitoringGroupMemberInfo
        /// </summary>
        [Test]
        public void CallMonitoringGroupMemberInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CallMonitoringGroupMemberInfo
            //Assert.IsInstanceOf(typeof(CallMonitoringGroupMemberInfo), instance);
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExtensionNumber'
        /// </summary>
        [Test]
        public void ExtensionNumberTest()
        {
            // TODO unit test for the property 'ExtensionNumber'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Test]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

    }

}
