/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CustomCompanyGreetingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomCompanyGreetingInfoTests
    {
        // TODO uncomment below to declare an instance variable for CustomCompanyGreetingInfo
        //private CustomCompanyGreetingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomCompanyGreetingInfo
            //instance = new CustomCompanyGreetingInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomCompanyGreetingInfo
        /// </summary>
        [Test]
        public void CustomCompanyGreetingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CustomCompanyGreetingInfo
            //Assert.IsInstanceOf(typeof(CustomCompanyGreetingInfo), instance);
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'ContentUri'
        /// </summary>
        [Test]
        public void ContentUriTest()
        {
            // TODO unit test for the property 'ContentUri'
        }
        /// <summary>
        /// Test the property 'AnsweringRule'
        /// </summary>
        [Test]
        public void AnsweringRuleTest()
        {
            // TODO unit test for the property 'AnsweringRule'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

    }

}
