/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ForwardingNumberShortInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ForwardingNumberShortInfoTests
    {
        // TODO uncomment below to declare an instance variable for ForwardingNumberShortInfo
        //private ForwardingNumberShortInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForwardingNumberShortInfo
            //instance = new ForwardingNumberShortInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForwardingNumberShortInfo
        /// </summary>
        [Test]
        public void ForwardingNumberShortInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ForwardingNumberShortInfo
            //Assert.IsInstanceOf(typeof(ForwardingNumberShortInfo), instance);
        }


        /// <summary>
        /// Test the property 'ForwardingNumberId'
        /// </summary>
        [Test]
        public void ForwardingNumberIdTest()
        {
            // TODO unit test for the property 'ForwardingNumberId'
        }

    }

}
