/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetAccountInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAccountInfoResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetAccountInfoResponse
        //private GetAccountInfoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAccountInfoResponse
            //instance = new GetAccountInfoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAccountInfoResponse
        /// </summary>
        [Test]
        public void GetAccountInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetAccountInfoResponse
            //Assert.IsInstanceOf(typeof(GetAccountInfoResponse), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'Bsid'
        /// </summary>
        [Test]
        public void BsidTest()
        {
            // TODO unit test for the property 'Bsid'
        }
        /// <summary>
        /// Test the property 'MainNumber'
        /// </summary>
        [Test]
        public void MainNumberTest()
        {
            // TODO unit test for the property 'MainNumber'
        }
        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Test]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
        /// <summary>
        /// Test the property 'PartnerId'
        /// </summary>
        [Test]
        public void PartnerIdTest()
        {
            // TODO unit test for the property 'PartnerId'
        }
        /// <summary>
        /// Test the property 'ServiceInfo'
        /// </summary>
        [Test]
        public void ServiceInfoTest()
        {
            // TODO unit test for the property 'ServiceInfo'
        }
        /// <summary>
        /// Test the property 'SetupWizardState'
        /// </summary>
        [Test]
        public void SetupWizardStateTest()
        {
            // TODO unit test for the property 'SetupWizardState'
        }
        /// <summary>
        /// Test the property 'SignupInfo'
        /// </summary>
        [Test]
        public void SignupInfoTest()
        {
            // TODO unit test for the property 'SignupInfo'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusInfo'
        /// </summary>
        [Test]
        public void StatusInfoTest()
        {
            // TODO unit test for the property 'StatusInfo'
        }
        /// <summary>
        /// Test the property 'RegionalSettings'
        /// </summary>
        [Test]
        public void RegionalSettingsTest()
        {
            // TODO unit test for the property 'RegionalSettings'
        }
        /// <summary>
        /// Test the property 'Federated'
        /// </summary>
        [Test]
        public void FederatedTest()
        {
            // TODO unit test for the property 'Federated'
        }
        /// <summary>
        /// Test the property 'OutboundCallPrefix'
        /// </summary>
        [Test]
        public void OutboundCallPrefixTest()
        {
            // TODO unit test for the property 'OutboundCallPrefix'
        }
        /// <summary>
        /// Test the property 'Cfid'
        /// </summary>
        [Test]
        public void CfidTest()
        {
            // TODO unit test for the property 'Cfid'
        }
        /// <summary>
        /// Test the property 'Limits'
        /// </summary>
        [Test]
        public void LimitsTest()
        {
            // TODO unit test for the property 'Limits'
        }

    }

}
