/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetLocationDeletionMultiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetLocationDeletionMultiResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetLocationDeletionMultiResponse
        //private GetLocationDeletionMultiResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetLocationDeletionMultiResponse
            //instance = new GetLocationDeletionMultiResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetLocationDeletionMultiResponse
        /// </summary>
        [Test]
        public void GetLocationDeletionMultiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetLocationDeletionMultiResponse
            //Assert.IsInstanceOf(typeof(GetLocationDeletionMultiResponse), instance);
        }


        /// <summary>
        /// Test the property 'Deletion'
        /// </summary>
        [Test]
        public void DeletionTest()
        {
            // TODO unit test for the property 'Deletion'
        }
        /// <summary>
        /// Test the property 'Reassignment'
        /// </summary>
        [Test]
        public void ReassignmentTest()
        {
            // TODO unit test for the property 'Reassignment'
        }
        /// <summary>
        /// Test the property 'EmergencyLocations'
        /// </summary>
        [Test]
        public void EmergencyLocationsTest()
        {
            // TODO unit test for the property 'EmergencyLocations'
        }

    }

}
