/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GlipPostEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GlipPostEventTests
    {
        // TODO uncomment below to declare an instance variable for GlipPostEvent
        //private GlipPostEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GlipPostEvent
            //instance = new GlipPostEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GlipPostEvent
        /// </summary>
        [Test]
        public void GlipPostEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GlipPostEvent
            //Assert.IsInstanceOf(typeof(GlipPostEvent), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Test]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'CreatorId'
        /// </summary>
        [Test]
        public void CreatorIdTest()
        {
            // TODO unit test for the property 'CreatorId'
        }
        /// <summary>
        /// Test the property 'AddedPersonIds'
        /// </summary>
        [Test]
        public void AddedPersonIdsTest()
        {
            // TODO unit test for the property 'AddedPersonIds'
        }
        /// <summary>
        /// Test the property 'RemovedPersonIds'
        /// </summary>
        [Test]
        public void RemovedPersonIdsTest()
        {
            // TODO unit test for the property 'RemovedPersonIds'
        }
        /// <summary>
        /// Test the property 'Mentions'
        /// </summary>
        [Test]
        public void MentionsTest()
        {
            // TODO unit test for the property 'Mentions'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedTime'
        /// </summary>
        [Test]
        public void LastModifiedTimeTest()
        {
            // TODO unit test for the property 'LastModifiedTime'
        }

    }

}
