/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MeetingServiceInfoResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeetingServiceInfoResourceTests
    {
        // TODO uncomment below to declare an instance variable for MeetingServiceInfoResource
        //private MeetingServiceInfoResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MeetingServiceInfoResource
            //instance = new MeetingServiceInfoResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MeetingServiceInfoResource
        /// </summary>
        [Test]
        public void MeetingServiceInfoResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MeetingServiceInfoResource
            //Assert.IsInstanceOf(typeof(MeetingServiceInfoResource), instance);
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'SupportUri'
        /// </summary>
        [Test]
        public void SupportUriTest()
        {
            // TODO unit test for the property 'SupportUri'
        }
        /// <summary>
        /// Test the property 'IntlDialInNumbersUri'
        /// </summary>
        [Test]
        public void IntlDialInNumbersUriTest()
        {
            // TODO unit test for the property 'IntlDialInNumbersUri'
        }
        /// <summary>
        /// Test the property 'ExternalUserInfo'
        /// </summary>
        [Test]
        public void ExternalUserInfoTest()
        {
            // TODO unit test for the property 'ExternalUserInfo'
        }
        /// <summary>
        /// Test the property 'DialInNumbers'
        /// </summary>
        [Test]
        public void DialInNumbersTest()
        {
            // TODO unit test for the property 'DialInNumbers'
        }

    }

}
