/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MessageStatusCounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageStatusCountsTests
    {
        // TODO uncomment below to declare an instance variable for MessageStatusCounts
        //private MessageStatusCounts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageStatusCounts
            //instance = new MessageStatusCounts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageStatusCounts
        /// </summary>
        [Test]
        public void MessageStatusCountsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MessageStatusCounts
            //Assert.IsInstanceOf(typeof(MessageStatusCounts), instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'ErrorCodeCounts'
        /// </summary>
        [Test]
        public void ErrorCodeCountsTest()
        {
            // TODO unit test for the property 'ErrorCodeCounts'
        }

    }

}
