/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MessageStoreConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageStoreConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for MessageStoreConfiguration
        //private MessageStoreConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageStoreConfiguration
            //instance = new MessageStoreConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageStoreConfiguration
        /// </summary>
        [Test]
        public void MessageStoreConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MessageStoreConfiguration
            //Assert.IsInstanceOf(typeof(MessageStoreConfiguration), instance);
        }


        /// <summary>
        /// Test the property 'RetentionPeriod'
        /// </summary>
        [Test]
        public void RetentionPeriodTest()
        {
            // TODO unit test for the property 'RetentionPeriod'
        }

    }

}
