/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TelephonyUserMeetingSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TelephonyUserMeetingSettingsTests
    {
        // TODO uncomment below to declare an instance variable for TelephonyUserMeetingSettings
        //private TelephonyUserMeetingSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TelephonyUserMeetingSettings
            //instance = new TelephonyUserMeetingSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TelephonyUserMeetingSettings
        /// </summary>
        [Test]
        public void TelephonyUserMeetingSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TelephonyUserMeetingSettings
            //Assert.IsInstanceOf(typeof(TelephonyUserMeetingSettings), instance);
        }


        /// <summary>
        /// Test the property 'ThirdPartyAudio'
        /// </summary>
        [Test]
        public void ThirdPartyAudioTest()
        {
            // TODO unit test for the property 'ThirdPartyAudio'
        }
        /// <summary>
        /// Test the property 'AudioConferenceInfo'
        /// </summary>
        [Test]
        public void AudioConferenceInfoTest()
        {
            // TODO unit test for the property 'AudioConferenceInfo'
        }

    }

}
