/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UpdateSwitchInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSwitchInfoTests
    {
        // TODO uncomment below to declare an instance variable for UpdateSwitchInfo
        //private UpdateSwitchInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateSwitchInfo
            //instance = new UpdateSwitchInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateSwitchInfo
        /// </summary>
        [Test]
        public void UpdateSwitchInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateSwitchInfo
            //Assert.IsInstanceOf(typeof(UpdateSwitchInfo), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ChassisId'
        /// </summary>
        [Test]
        public void ChassisIdTest()
        {
            // TODO unit test for the property 'ChassisId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Site'
        /// </summary>
        [Test]
        public void SiteTest()
        {
            // TODO unit test for the property 'Site'
        }
        /// <summary>
        /// Test the property 'EmergencyAddress'
        /// </summary>
        [Test]
        public void EmergencyAddressTest()
        {
            // TODO unit test for the property 'EmergencyAddress'
        }
        /// <summary>
        /// Test the property 'EmergencyLocationId'
        /// </summary>
        [Test]
        public void EmergencyLocationIdTest()
        {
            // TODO unit test for the property 'EmergencyLocationId'
        }
        /// <summary>
        /// Test the property 'EmergencyLocation'
        /// </summary>
        [Test]
        public void EmergencyLocationTest()
        {
            // TODO unit test for the property 'EmergencyLocation'
        }

    }

}
