/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ValidateMultipleWirelessPointsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidateMultipleWirelessPointsRequestTests
    {
        // TODO uncomment below to declare an instance variable for ValidateMultipleWirelessPointsRequest
        //private ValidateMultipleWirelessPointsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValidateMultipleWirelessPointsRequest
            //instance = new ValidateMultipleWirelessPointsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidateMultipleWirelessPointsRequest
        /// </summary>
        [Test]
        public void ValidateMultipleWirelessPointsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ValidateMultipleWirelessPointsRequest
            //Assert.IsInstanceOf(typeof(ValidateMultipleWirelessPointsRequest), instance);
        }


        /// <summary>
        /// Test the property 'Records'
        /// </summary>
        [Test]
        public void RecordsTest()
        {
            // TODO unit test for the property 'Records'
        }

    }

}
