/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing WeeklyScheduleInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WeeklyScheduleInfoTests
    {
        // TODO uncomment below to declare an instance variable for WeeklyScheduleInfo
        //private WeeklyScheduleInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WeeklyScheduleInfo
            //instance = new WeeklyScheduleInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WeeklyScheduleInfo
        /// </summary>
        [Test]
        public void WeeklyScheduleInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WeeklyScheduleInfo
            //Assert.IsInstanceOf(typeof(WeeklyScheduleInfo), instance);
        }


        /// <summary>
        /// Test the property 'Monday'
        /// </summary>
        [Test]
        public void MondayTest()
        {
            // TODO unit test for the property 'Monday'
        }
        /// <summary>
        /// Test the property 'Tuesday'
        /// </summary>
        [Test]
        public void TuesdayTest()
        {
            // TODO unit test for the property 'Tuesday'
        }
        /// <summary>
        /// Test the property 'Wednesday'
        /// </summary>
        [Test]
        public void WednesdayTest()
        {
            // TODO unit test for the property 'Wednesday'
        }
        /// <summary>
        /// Test the property 'Thursday'
        /// </summary>
        [Test]
        public void ThursdayTest()
        {
            // TODO unit test for the property 'Thursday'
        }
        /// <summary>
        /// Test the property 'Friday'
        /// </summary>
        [Test]
        public void FridayTest()
        {
            // TODO unit test for the property 'Friday'
        }
        /// <summary>
        /// Test the property 'Saturday'
        /// </summary>
        [Test]
        public void SaturdayTest()
        {
            // TODO unit test for the property 'Saturday'
        }
        /// <summary>
        /// Test the property 'Sunday'
        /// </summary>
        [Test]
        public void SundayTest()
        {
            // TODO unit test for the property 'Sunday'
        }

    }

}
