/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: platform@ringcentral.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing VideoConfigurationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class VideoConfigurationApiTests
    {
        private VideoConfigurationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new VideoConfigurationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VideoConfigurationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' VideoConfigurationApi
            //Assert.IsInstanceOf(typeof(VideoConfigurationApi), instance);
        }

        
        /// <summary>
        /// Test ReadUserVideoConfiguration
        /// </summary>
        [Test]
        public void ReadUserVideoConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string extensionId = null;
            //var response = instance.ReadUserVideoConfiguration(accountId, extensionId);
            //Assert.IsInstanceOf(typeof(UserVideoConfiguration), response, "response is UserVideoConfiguration");
        }
        
        /// <summary>
        /// Test UpdateUserVideoConfiguration
        /// </summary>
        [Test]
        public void UpdateUserVideoConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string extensionId = null;
            //UserVideoConfiguration userVideoConfiguration = null;
            //var response = instance.UpdateUserVideoConfiguration(accountId, extensionId, userVideoConfiguration);
            //Assert.IsInstanceOf(typeof(UserVideoConfiguration), response, "response is UserVideoConfiguration");
        }
        
    }

}
